apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: db
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/vishv/data/postgresql
