apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
type: Opaque
data:
  POSTGRES_USER: dmlzaHY=         # "vishv" base64
  POSTGRES_PASSWORD: YWRtaW4xMjM= # "admin123" base64
  POSTGRES_DB: bXlkYXRhYmFzZQ==   # "mydatabase" base64
